# Generated by Django 4.2.5 on 2026-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_experience_alter_booking_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
