# Generated by Django 4.2.5 on 2026-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0004_alter_photo_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_scan", "검토 중"),
                    ("approved", "승인됨"),
                    ("rejected", "거부됨"),
                ],
                default="pending_scan",
                max_length=20,
            ),
        ),
    ]
