# Generated by Django 4.2.5 on 2026-03-12 12:38

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_alter_room_amenities_alter_room_category_and_more"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;", "SELECT 1;"),
        migrations.AddField(
            model_name="room",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
