services:
  - type: web
    name: airbnbclone
    runtime: python
    region: singapore
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: GH_SECRET
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER
        value: true
