# Generated by Django 4.2.5 on 2026-03-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="cards",
            field=models.JSONField(
                blank=True, default=list, verbose_name="카드 데이터"
            ),
        ),
    ]
