# Generated by Django 4.2.5 on 2026-03-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_chatlog_cards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotconfig",
            name="model_name",
            field=models.CharField(
                default="gpt-5-mini", max_length=50, verbose_name="모델명"
            ),
        ),
    ]
