# Generated by Django 4.2.5 on 2026-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_alter_chatbotconfig_model_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotconfig",
            name="model_name",
            field=models.CharField(
                default="gpt-4o-mini", max_length=50, verbose_name="모델명"
            ),
        ),
    ]
